class_name Sound
extends Node
## Plays the game's sound effects and music (all generated by
## tools/audio/make_audio.py, see audio/).
##
## Effects: Sound.play("kill_0") from anywhere. A pool of players is shared,
## and each sound has a minimum gap between plays and a cap on how many play
## at once, so a thousand kills a second stay a crunchy patter instead of a
## wall of noise.
##
## Music: each realm has a "calm" loop and a "drums" loop that run in sync;
## set_intensity() fades the drums in as the night gets dangerous, and
## set_boss() brings in the shared boss layer. Everything goes through the
## "Music" and "SFX" buses so the volume settings can scale them.

const POOL_SIZE := 28

## name -> [min seconds between plays, volume dB, pitch variation, max at once]
const RULES := {
	"bolt_cast": [0.09, -14.0, 0.08, 2],
	"bolt_hit": [0.035, -17.0, 0.15, 3],
	"kill_0": [0.03, -13.0, 0.18, 4], "kill_1": [0.03, -13.0, 0.18, 4], "kill_2": [0.03, -13.0, 0.18, 4],
	"elite_kill": [0.1, -4.0, 0.05, 2],
	"gem": [0.035, -15.0, 0.0, 4],
	"soul": [0.08, -10.0, 0.06, 2],
	"loot": [0.1, -8.0, 0.0, 2],
	"legendary": [0.3, -2.0, 0.0, 1],
	"pickup": [0.08, -9.0, 0.05, 2],
	"levelup": [0.3, -5.0, 0.0, 1],
	"ui_hover": [0.03, -18.0, 0.04, 2],
	"ui_click": [0.05, -10.0, 0.0, 2],
	"card_pick": [0.1, -6.0, 0.0, 1],
	"reroll": [0.1, -8.0, 0.0, 1],
	"dash": [0.1, -8.0, 0.08, 1],
	"hurt": [0.35, -9.0, 0.1, 1],
	"lightning": [0.08, -11.0, 0.12, 2],
	"nova": [0.15, -6.0, 0.05, 1],
	"blade": [0.09, -19.0, 0.2, 2],
	"shatter": [0.12, -9.0, 0.1, 2],
	"melt": [0.12, -12.0, 0.1, 2],
	"overload": [0.12, -8.0, 0.1, 2],
	"ignite": [0.2, -17.0, 0.15, 1],
	"boss_roar": [1.0, -3.0, 0.05, 1],
	"boss_arrive": [1.0, -4.0, 0.0, 1],
	"slam": [0.3, -3.0, 0.05, 2],
	"telegraph": [0.4, -16.0, 0.0, 2],
	"meteor": [0.2, -7.0, 0.1, 2],
	"ice_impact": [0.2, -9.0, 0.1, 2],
	"grave": [0.3, -6.0, 0.1, 1],
	"minion_raise": [0.3, -6.0, 0.05, 1],
	"minion_death": [0.2, -12.0, 0.1, 1],
	"chest": [0.3, -5.0, 0.0, 1],
	"shrine_charge": [0.9, -14.0, 0.0, 1],
	"shrine_done": [0.5, -4.0, 0.0, 1],
	"goblin": [0.8, -8.0, 0.1, 1],
	"heal": [0.2, -8.0, 0.0, 1],
	"victory": [2.0, -2.0, 0.0, 1],
	"defeat": [2.0, -3.0, 0.0, 1],
}

static var instance: Sound

var _streams := {}
var _players: Array[AudioStreamPlayer] = []
var _next := 0
var _last := {}
var _calm: AudioStreamPlayer
var _drums: AudioStreamPlayer
var _boss: AudioStreamPlayer
var _realm := ""
var _intensity := 0.0
var _intensity_target := 0.0
var _boss_mix := 0.0
var _boss_target := 0.0
var _music_on := true


## Effects anywhere in the game: Sound.play("gem", 1.2) (pitch scale 1.2).
static func play(sound: String, pitch := 1.0, volume_offset := 0.0) -> void:
	if instance:
		instance._play(sound, pitch, volume_offset)


func _enter_tree() -> void:
	instance = self
	process_mode = Node.PROCESS_MODE_ALWAYS


func _exit_tree() -> void:
	if instance == self:
		instance = null


func _ready() -> void:
	_ensure_bus("Music")
	_ensure_bus("SFX")
	apply_volumes()
	for i in POOL_SIZE:
		var p := AudioStreamPlayer.new()
		p.bus = "SFX"
		add_child(p)
		_players.append(p)
	for sound: String in RULES:
		var path := "res://audio/sfx/%s.wav" % sound
		if ResourceLoader.exists(path):
			_streams[sound] = load(path)
	_calm = _music_player()
	_drums = _music_player()
	_boss = _music_player()
	var boss_stream := _loop("res://audio/music/boss.ogg")
	if boss_stream:
		_boss.stream = boss_stream


## Sets the bus volumes from the saved settings.
static func apply_volumes() -> void:
	for bus_name: String in ["Music", "SFX"]:
		var bus := AudioServer.get_bus_index(bus_name)
		if bus < 0:
			continue
		var v: float = MetaProgress.setting("music_volume" if bus_name == "Music" else "sfx_volume")
		AudioServer.set_bus_volume_db(bus, linear_to_db(maxf(v, 0.0001)))
		AudioServer.set_bus_mute(bus, v <= 0.001)


## Starts (or crossfades to) a realm's music.
func play_realm(realm_id: String) -> void:
	if realm_id == _realm:
		return
	_realm = realm_id
	var calm := _loop("res://audio/music/%s_calm.ogg" % realm_id)
	var drums := _loop("res://audio/music/%s_drums.ogg" % realm_id)
	if calm == null:
		return
	_music_on = true
	_calm.stream = calm
	_drums.stream = drums
	_calm.play()
	_drums.play()
	if _boss.stream:
		_boss.play()
	_calm.volume_db = -40.0
	create_tween().tween_property(_calm, "volume_db", 0.0, 1.5)


## 0 = calm (drums silent), 1 = full drums.
func set_intensity(value: float) -> void:
	_intensity_target = clampf(value, 0.0, 1.0)


func set_boss(on: bool) -> void:
	_boss_target = 1.0 if on else 0.0


## Fades the music out (before the victory and defeat stings).
func stop_music(fade := 1.0) -> void:
	_music_on = false
	for p in [_calm, _drums, _boss]:
		create_tween().tween_property(p, "volume_db", -60.0, fade)


func _process(delta: float) -> void:
	if not _music_on:
		return
	_intensity = move_toward(_intensity, _intensity_target, delta * 0.15)
	_boss_mix = move_toward(_boss_mix, _boss_target, delta * 0.4)
	# Keep the layers locked together: the drums and boss loops follow the calm one.
	if _calm.playing:
		var pos := _calm.get_playback_position()
		for p: AudioStreamPlayer in [_drums, _boss]:
			if p.playing and absf(p.get_playback_position() - pos) > 0.08:
				p.seek(pos)
	_drums.volume_db = linear_to_db(maxf(lerpf(0.12, 1.0, _intensity), 0.0001))
	_boss.volume_db = linear_to_db(maxf(_boss_mix * 0.95, 0.0001))


func _play(sound: String, pitch: float, volume_offset: float) -> void:
	var stream: AudioStream = _streams.get(sound)
	if stream == null:
		return
	var rule: Array = RULES[sound]
	var now := Time.get_ticks_msec() / 1000.0
	if now - _last.get(sound, -10.0) < rule[0]:
		return
	var playing := 0
	for p in _players:
		if p.playing and p.stream == stream:
			playing += 1
	if playing >= rule[3]:
		return
	_last[sound] = now
	var player := _players[_next]
	_next = (_next + 1) % _players.size()
	player.stream = stream
	player.volume_db = rule[1] + volume_offset
	player.pitch_scale = pitch * (1.0 + randf_range(-rule[2], rule[2]))
	player.play()


func _music_player() -> AudioStreamPlayer:
	var p := AudioStreamPlayer.new()
	p.bus = "Music"
	add_child(p)
	return p


func _loop(path: String) -> AudioStream:
	if not ResourceLoader.exists(path):
		return null
	var s = load(path)
	if s is AudioStreamOggVorbis:
		(s as AudioStreamOggVorbis).loop = true
	return s


static func _ensure_bus(bus_name: String) -> void:
	if AudioServer.get_bus_index(bus_name) >= 0:
		return
	AudioServer.add_bus()
	var i := AudioServer.bus_count - 1
	AudioServer.set_bus_name(i, bus_name)
	AudioServer.set_bus_send(i, "Master")
